### ISSUE TITLE
tm.temperature scroll for negative and > 99 values

### ISSUE THREAD

**Issue by thijstriemstra** [mcauser/micropython-tm1637#8]
A DS18B20 measures temperatures from -55°C to +125°C. With `tm.temperature(101)` as well as `tm.temperature(-10)` it shows garbled text. Is it possible to simply scroll for values over > 99 or < -9? Also see https://github.com/mcauser/micropython-tm1637/blob/master/tm1637_test.py#L209

I can create a PR if you like the idea.

**Comment by thijstriemstra** [comment]
![img_20180801_024155](https://user-images.githubusercontent.com/305679/43494743-9a4b1754-9534-11e8-9f14-85016e9f76ec.jpg)

**Comment by mcauser** [comment]
I added the `temperature()` method which shows a "degrees C" on the last 2 segments.
This means it's possible range is -9 to +99.

To show _something_ when outside this range, I added "HI" for High and "LO" for Low.
eg.
```
tm.temperature(-10) # LO*C
tm.temperature(-9)  # -9*C
tm.temperature(5)   #  5*C
tm.temperature(24)   # 24*C
tm.temperature(99)  # 99*C
tm.temperature(100) # HI*C
```

Another way of writing `tm.temperature(24)` is `tm.show('24*C')`.

To support a wider range of temperatures / numbers, you could stringify your number and call `scroll()` instead of `show()`, with '*C' as the last 2 characters in your string if you want to represent it as a temperature. The star '*' symbol is displayed as a degrees symbol, the top 4 LED segments.

**Comment by thijstriemstra** [comment]
Ah I see, it says LO/HI! Sorry for calling it garbled text ;) I will try to come up with a scrolling version, at least for my own project, and let you know how it goes.

**Comment by mcauser** [comment]
Sounds like this is what you're after:
```
def ds18b20(self, temp, delay=250):
	self.scroll('{:.0f}*C'.format(temp), delay)
```

**Comment by thijstriemstra** [comment]
@mcauser that's beautiful! having that as the default for `temperature` would be a nice enhancement.
